SET C51INC=C:\Program Files (x86)\keil51\C51\Inc;C:\Program Files (x86)\keil51\C51\Inc\Atmel
SET C51LIB=C:\Program Files (x86)\keil51\C51\Lib
SET CPU_TYPE=AT89C51
SET CPU_VENDOR=Microchip
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x016E3600
"C:\Program Files (x86)\keil51\C51\BIN\A51.EXE" @".\Objects\STARTUP._ia"
"C:\Program Files (x86)\keil51\C51\BIN\C51.EXE" @".\Objects\main.__i"
"C:\Program Files (x86)\keil51\C51\BIN\BL51.EXE" @".\Objects\…¡À∏µ∆.lnp"
"C:\Program Files (x86)\keil51\C51\BIN\OH51.EXE" ".\Objects\…¡À∏µ∆" 
